# youtube-dl -o YJIIWD.mp4 "https://www.youtube.com/watch?v=z6ep308goxQ"

name: dl
on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U youtube-dl aliyunpan
          echo "refresh_token: '${{ secrets.ALYP }}'"  >  ~/.config/aliyunpan.yaml
          youtube-dl -o HCMJIDW.mp4 "https://www.youtube.com/watch?v=Opy-SjDU0UY"
          aliyunpan-cli upload HCMJIDW.mp4
