name: dl
on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U youtube-dl aliyunpan
          echo "refresh_token: '${{ secrets.ALYP }}'"  >  ~/.config/aliyunpan.yaml
          cat ~/.config/aliyunpan.yaml
          aliyunpan-cli list
          youtube-dl "https://www.youtube.com/watch?v=Opy-SjDU0UY"
          
